[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]

[build]
target = "aarch64-unknown-none-softfloat.json"
rustflags = "--cfg cxx_experimental_no_alloc"

[target.aarch64-unknown-none-softfloat]
runner = "./runner.sh"
