[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "aarch64-unknown-none-softfloat.json"

[target.aarch64-unknown-none-softfloat]
runner = "qemu-system-aarch64 -M raspi3b -cpu cortex-a53  -nographic -semihosting -kernel"
